### PR TITLE
Use CSS to make cursor blink.

### PR DESCRIPTION
**Pull request by rygwdn**

### CODE REVIEW

**Comment by coolwanglu** [comment]
That's a good idea! Can you make an option for this?

In the future, probably the cursor will be re-implemented as a solid box, with inversed color.

**Comment by rygwdn** [comment]
@coolwanglu: I added a config option for it. I started down the road of a more complicated cursor re-design, but decided to take this as a quick win for now. I'd like to support [`'guicursor'`](http://vimdoc.sourceforge.net/htmldoc/options.html#'guicursor'), but that needs the cursor to be drawn on the canvas instead of in a div (to support doing the optional inverse).

**Comment by coolwanglu** [comment]
@rygwdn Yes, I had thought of that, and in fact I was trying to draw the cursor on canvas in the first place. The problem is that we need to know the character and attrs under the cursor, but we cannot do that without saving the entire buffer. The Python client is doing this way, but I don't like to store the text. 

Feel free to move cursor on the canvas.

**Comment by coolwanglu** [comment]
Merged. Thanks!

**Pull request merged**
